

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID') if Rails.env=="production" %>
  aws_secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY') if Rails.env=="production" %>
  aws_bucket_name: <%= ENV.fetch('S3_BUCKET_NAME') if Rails.env=="production" %>
  google_app_id: <%= ENV.fetch('GOOGLE_APP_ID') if Rails.env=="production" %>
  google_app_key: <%= ENV.fetch('GOOGLE_APP_KEY') if Rails.env=="production" %>
  facebook_app_id: <%= ENV.fetch('FB_APP_ID') if Rails.env=="production" %>
  facebook_app_key: <%= ENV.fetch('FB_APP_KEY') if Rails.env=="production" %>


